### ISSUE TITLE
Tax links for USA

### ISSUE THREAD

**Issue by StarfallProjects** [StarfallProjects/consultant-tech-writer-toolkit#19]
The tax page currently only contains info for the UK: https://techwritertoolkit.com/resources/tax-links/ Add a similar section for the USA.

Guidance:

- Keep it short (similar to the UK section) This page is a starting point/collection of links, not a definitive guide.
- Provide links to official government guides, NOT to secondary articles or posts.

**Comment by firstladymb** [comment]
Just did a PR fo this!
